  name: WLED compile
on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://api.github.com/repos/MoonModules/WLED/zipball/v0.14.0.b27 -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32S3_8MB_M' >>platformio.ini
        echo 'build_flags = ${env:esp32S3_8MB_M.build_flags} ${common.debug_flags} -D SR_DEBUG -D WLED_USE_ETHERNET -D WLED_AP_SSID_UNIQUE -D WLED_ENABLE_PIXART -D CLIENT_SSID='\''"Sercomm4EE2"'\'' -D CLIENT_PASS='\''"86ZJ6CXW3DS39F"'\'' -D WLED_AP_SSID='\''""'\'' -D WLED_AP_PASS='\''""'\'' -D USERMOD_AUTO_SAVE -D USERMOD_FOUR_LINE_DISPLAY -D USERMOD_RTC -D RGB_ROTARY_ENCODER -D USERMOD_ADS1115 -D USERMOD_SEVEN_SEGMENT -D USERMOD_SSDR' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32S3_8MB_M.lib_deps}' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  lennarthennigs/ESP Rotary@^1.5.0' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        
        echo 'build_unflags= -D WLED_RELEASE_NAME' >>platformio.ini
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
